config/urls.py
from django.contrib import admin
from django.urls import include, path
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), #추가 항상 pybo/처럼 끝에 슬래시 붙여주기.
    path('common/', include('common.urls')),#http://localhost:8000/common/ 으로 시작하는 URL은 common/urls.py를 참조
    path('doubleboard/', include('doubleboard.urls')),
    path('minorboard/', include('minorboard.urls')),
    path('information/', include('information.urls')),
    path('free/', include('free.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

doubleboard/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views
#doubleboard앱 이외의 다른 앱이 프로젝트에 추가 될 경우 서로 다른 앱에서 동일한 URL 별칭을 사용한다면 중복이 발생 -> 네임스페이스선언.
app_name = 'doubleboard'

urlpatterns = [  #name으로 별칭사용 url규칙 바뀔경우 일일이 바꿔야함으로 별칭사용, int는 숫자값이 매핑됨을 의미.
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

free/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views
#free앱 이외의 다른 앱이 프로젝트에 추가 될 경우 서로 다른 앱에서 동일한 URL 별칭을 사용한다면 중복이 발생 -> 네임스페이스선언.
app_name = 'free'

urlpatterns = [  #name으로 별칭사용 url규칙 바뀔경우 일일이 바꿔야함으로 별칭사용, int는 숫자값이 매핑됨을 의미.
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question') #계정(사용자) 모델은 django.contrib.auth.models 패키지의 User이므로 글쓴이에 해당되는 author 속성은 User모델을 ForeignKey로 적용
    subject = models.CharField(max_length=200) #질문제목
    content = models.TextField() #글자수 제한 X
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)#질문이나 답변이 언제 수정되었는지 확인
    #null=True의 의미는 modify_date를 데이터베이스에 저장할때 null이 허용된다는 의미, blank=True의 의미는 입력 폼 데이터 체크시(form.is_valid()) 값이 없어도 오류를 내지 않는다는 의미
    voter = models.ManyToManyField(User, related_name='voter_question')  # voter 추가, ManyToManyField관계는 다대다관계의미.

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #답변해당질문
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) #댓글작성자
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)  # 댓글의 질문
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)  # 댓글의 답변

doubleboard/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerDoubleForm
from ..models import QuestionDouble, AnswerDouble

@login_required(login_url='common:login')#로그아웃 상태에서 @login_required 어노테이션이 적용된 함수가 호출되면 자동으로 로그인 화면으로 이동
def answer_create(request, question_id):
    """
    doubleboard 답변등록
    """
    question = get_object_or_404(QuestionDouble, pk=question_id)
    if request.method == "POST":
        form = AnswerDoubleForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author_double = request.user  # 추가한 속성 author 적용, reqeust.user는 현재 로그인한 계정의 User모델 객체
            answer.create_dat_double = timezone.now()
            answer.question_double = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('doubleboard:detail', question_id=question.id), answer.id))#redirect함수는 페이지 이동을 위해 장고가 제공하는 함수, #QuestionDouble과 AnswerDouble 모델은 서로 ForeignKey 로 연결되어 있기때문에  question.answer_set은 질문의 답변을 의미
    else:
        form = AnswerDoubleForm()
    context = {'question': question, 'form': form}
    return render(request, 'doubleboard/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    doubleboard 답변수정
    """
    answer = get_object_or_404(AnswerDouble, pk=answer_id)
    if request.user != answer.author_double:
        messages.error(request, '수정권한이 없습니다')
        return redirect('doubleboard:detail', question_id=answer.question_double.id)

    if request.method == "POST":
        form = AnswerDoubleForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author_double = request.user
            answer.modify_date_double = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('doubleboard:detail', question_id=answer.question_double.id), answer.id)) #doubleboard:detail url에 #answer_7와같은 앵커태그를 추가하기 위해 format, resolve_url사용. resolve_url은 실제 호출되는 url 문자열을 리턴해주는 장고함수.
    else:
        form = AnswerDoubleForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'doubleboard/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    doubleboard 답변삭제
    """
    answer = get_object_or_404(AnswerDouble, pk=answer_id)
    if request.user != answer.author_double:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('doubleboard:detail', question_id=answer.question_double.id)

doubleboard/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from ..models import QuestionDouble #부모 디렉터리에 존재하므로 ..붙여주기


def index(request): #request는 장고 프레임워크에 의해 자동으로 전달되는 HTTP 요청 객체
    """
    doubleboard 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지 (GET방식으로 요청한 URL에서 page의 값을 가져올때 사용)
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recommend':
        question_list = QuestionDouble.objects.annotate(num_voter=Count('voter_double')).order_by('-num_voter_double', '-create_date_double') #추천수는 장고의 annotate를 이용하여 Count함수를 통해 구할수있음.
    elif so == 'popular':
        question_list = QuestionDouble.objects.annotate(num_answer=Count('answer_double')).order_by('-num_answer_double', '-create_date_double')
    else:  # recent
        question_list = QuestionDouble.objects.order_by('-create_date_double')

    # 조회
    if kw:
        question_list = question_list.filter( #filter 함수안에서 모델속성에 접근할떄는 __이용시 하위 속성에 접근가능.
            Q(subject__icontains=kw) |  # 제목검색, icontains대신 contains사용시 대소문자 구분.
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기(Paginator는 조회된 question_list를 페이징 객체(paginator)로 변환)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}  # <------ so 추가 ,page와 kw가 추가.
    return render(request, 'doubleboard/question_list.html', context) #템플릿파일

def detail(request, question_id): #전달되는 매개변수가 request외에 question_id가 하나 더 추가
    """
    doubleboard 내용 출력
    """
    question = get_object_or_404(QuestionDouble, pk=question_id)#pk는 QuestionDouble모델의 기본키(Primary Key)인 id를 의미
    context = {'question': question}
    return render(request, 'doubleboard/question_detail.html', context)

doubleboard/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentDoubleForm
from ..models import QuestionDouble, AnswerDouble, CommentDouble

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    doubleboard 질문댓글등록
    """
    question = get_object_or_404(QuestionDouble, pk=question_id)
    if request.method == "POST":
        form = CommentDoubleForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author_double = request.user
            comment.create_date_double = timezone.now()
            comment.question_double = question #질문에 대한 댓글이므로 comment에 question저장.
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('doubleboard:detail', question_id=comment.question_double.id), comment.id))
    else:
        form = CommentDoubleForm()
    context = {'form': form}
    return render(request, 'doubleboard/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    doubleboard 질문댓글수정
    """
    comment = get_object_or_404(CommentDouble, pk=comment_id)
    if request.user != comment.author_double:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('doubleboard:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentDoubleForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author_double = request.user
            comment.modify_date_double = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('doubleboard:detail', question_id=comment.question_double.id), comment.id))
    else:
        form = CommentDoubleForm(instance=comment)
    context = {'form': form}
    return render(request, 'doubleboard/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    doubleboard 질문댓글삭제
    """
    comment = get_object_or_404(CommentDouble, pk=comment_id)
    if request.user != comment.author_double:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('doubleboard:detail', question_id=comment.question_id)
    else:
        comment.delete()
    return redirect('doubleboard:detail', question_id=comment.question_id)

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    doubleboard 답글댓글등록
    """
    answer = get_object_or_404(AnswerDouble, pk=answer_id)
    if request.method == "POST":
        form = CommentDoubleForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author_double = request.user
            comment.create_date_double = timezone.now()
            comment.answer_double = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('doubleboard:detail', question_id=comment.answer_double.question_double.id), comment.id))
    else:
        form = CommentDoubleForm()
    context = {'form': form}
    return render(request, 'doubleboard/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    doubleboard 답글댓글수정
    """
    comment = get_object_or_404(CommentDouble, pk=comment_id)
    if request.user != comment.author_double:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('doubleboard:detail', question_id=comment.answer_double.question_double.id)

    if request.method == "POST":
        form = CommentDoubleForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author_double = request.user
            comment.modify_date_double = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('doubleboard:detail', question_id=comment.answer_double.question_double.id), comment.id))
    else:
        form = CommentDoubleForm(instance=comment)
    context = {'form': form}
    return render(request, 'doubleboard/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    doubleboard 답글댓글삭제
    """
    comment = get_object_or_404(CommentDouble, pk=comment_id)
    if request.user != comment.author_double:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('doubleboard:detail', question_id=comment.answer_double.question_double.id)
    else:
        comment.delete()
    return redirect('doubleboard:detail', question_id=comment.answer_double.question_double.id)

doubleboard/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import QuestionDouble, AnswerDouble


@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    doubleboard 질문추천등록
    """
    question = get_object_or_404(QuestionDouble, pk=question_id)
    if request.user == question.author_double:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter_double.add(request.user)
    return redirect('doubleboard:detail', question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    doubleboard 답글추천등록
    """
    answer = get_object_or_404(AnswerDouble, pk=answer_id)
    if request.user == answer.author_double:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter_double.add(request.user)
    return redirect('doubleboard:detail', question_id=answer.question_double.id)

templates/doubleboard/answer_form.html
{% extends 'doubleboard.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content_double">답변내용</label>
            <textarea class="form-control" name="content_double" id="content_double" 
                      rows="10">{{ form.content_double.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/doubleboard/comment_form.html
{% extends 'doubleboard.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content_double">댓글내용</label>
            <textarea class="form-control"name="content_double" id="content_double" 
                      rows="3">{{ form.content_double.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/doubleboard/question_detail.html
{% extends 'doubleboard.html' %}
{% block content %}

<div class="container my-3">  <!--질문이나 답변들은 하나의 뭉치에 해당되므로 부트스트랩의 card 컴포넌트를 사용-->
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject_double }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter_double.count}}</div>
            <a href="#" data-uri="{% url 'doubleboard:vote_question' question.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문영역 -->
            <div class="card"> <!--my-3은 위아래 방향 마진 3을 의미-->
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ question.content_double }}</div> <!--글 내용에 줄 바꿈을 정상적으로 보여주기위해 적용한 스타일-->
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date_double %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date_double }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left"><!--p-2는 padding 2를 의미-->
                            <div class="mb-2">{{ question.author_double.username }}</div>
                            <div>{{ question.create_date_double }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author_double %}
                    <div class="my-3"><!--수정 버튼은 로그인한 사용자와 글쓴이가 동일한 경우에만 노출되도록 {% if request.user == question.author_double %}을 적용-->
                        <a href="{% url 'doubleboard:question_modify' question.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'doubleboard:question_delete' question.id  %}">삭제</a> <!--data-uri 속성은 jQuery에서 $(this).data('uri') 와 같이 사용하여 그 값을 얻을 수 있음-->
                    </div>
                    {% endif %}

                    <!-- 질문 댓글 Start -->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set.all %} <!--질문에 등록된 댓글을 모두 보여줌.-->
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted"> <!--댓글 영역은 작게 나타내기 위해 comment 클래스 사용 설정-->
                            <span style="white-space: pre-line;">{{ comment.content_double }}</span>
                            <span>
                                - {{ comment.author_double }}, {{ comment.create_date_double }}
                                {% if comment.modify_date_double %}
                                (수정:{{ comment.modify_date_double }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author_double %} <!--댓글 작성자와 로그인한 사람 같을 시 수정, 삭제 창 보이도록-->
                            <a href="{% url 'doubleboard:comment_modify_question' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'doubleboard:comment_delete_question' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'doubleboard:comment_create_question' question.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 질문 댓글 End -->
                </div>
            </div>
        </div>
    </div>

    <!--답변구역-->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a> <!--앵커태그-->
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter_double.count}}</div>
            <a href="#" data-uri="{% url 'doubleboard:vote_answer' answer.id  %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">  <!-- 답변영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content_double }}</div> <!--글 내용에 줄 바꿈을 정상적으로 보여주기위해 적용한 스타일-->
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date_double %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date_double }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.author_double.username }}</div>
                            <div>{{ answer.create_date_double }}</div>
                        </div>
                    </div>
                    {% if request.user == answer.author_double %}
                    <div class="my-3">
                        <a href="{% url 'doubleboard:answer_modify' answer.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                           data-uri="{% url 'doubleboard:answer_delete' answer.id  %}">삭제</a>
                    </div>
                    {% endif %}
                    <!--답변 댓글 start-->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content_double }}</span>
                            <span>
                                - {{ comment.author_double }}, {{ comment.create_date_double }}
                                {% if comment.modify_date_double %}
                                (수정:{{ comment.modify_date_double }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author_double %}
                            <a href="{% url 'doubleboard:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'doubleboard:comment_delete_answer' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'doubleboard:comment_create_answer' answer.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'doubleboard:answer_create' question.id %}" method="post" class="my-3"> <!--답변을 저장하는 URL-->
        {% csrf_token %} <!--보안에 관련된 항목으로 form으로 전송된 데이터가 실제 웹페이지에서 작성된 데이터인지를 판단해 주는 가늠자 역할-->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group"><!--답변을 작성하는 textarea에 로그인 상태가 아니라면 disabled 를 지정하여 입력자체를 불가능-->
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content_double" id="content_double" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endif %}  <!--여기 수정해야돼 글쓴이 아니면 답변등록 안됨-->
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/doubleboard/question_form.html
{% extends 'doubleboard.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">새 글을 작성해주세요!</h5>
    <form method="post" class="post-form my-3"> <!-- form태그의 action속성이 없는 경우는 현재의 페이지로 전송-->
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject_double">제목</label>
            <input type="text" class="form-control" name="subject_double" id="subject_double"
                   value="{{ form.subject_double.value|default_if_none:'' }}"> <!--오류가 발생했을 경우 기존에 입력했던 값을 유지-->
        </div>                                                          <!--|default_if_none:''의 의미는 폼 데이터(form.subject.value)에 값이 없을 경우 None 이라는 문자열이 표시되는데 None 대신 공백으로 표시하기 위한 필터-->
        <div class="form-group">
            <label for="content_double">내용</label>
            <textarea class="form-control" name="content_double"
                      id="content_double" rows="10">{{ form.content_double.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}