config/urls.py
from django.contrib import admin
from django.urls import include, path
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), #추가 항상 pybo/처럼 끝에 슬래시 붙여주기.
    path('common/', include('common.urls')),#http://localhost:8000/common/ 으로 시작하는 URL은 common/urls.py를 참조
    path('doubleboard/', include('doubleboard.urls')),
    path('minorboard/', include('minorboard.urls')),
    path('information/', include('information.urls')),
    path('free/', include('free.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

free/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views
#free앱 이외의 다른 앱이 프로젝트에 추가 될 경우 서로 다른 앱에서 동일한 URL 별칭을 사용한다면 중복이 발생 -> 네임스페이스선언.
app_name = 'free'

urlpatterns = [  #name으로 별칭사용 url규칙 바뀔경우 일일이 바꿔야함으로 별칭사용, int는 숫자값이 매핑됨을 의미.
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

minorboard/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views
#minorboard앱 이외의 다른 앱이 프로젝트에 추가 될 경우 서로 다른 앱에서 동일한 URL 별칭을 사용한다면 중복이 발생 -> 네임스페이스선언.
app_name = 'minorboard'

urlpatterns = [  #name으로 별칭사용 url규칙 바뀔경우 일일이 바꿔야함으로 별칭사용, int는 숫자값이 매핑됨을 의미.
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question') #계정(사용자) 모델은 django.contrib.auth.models 패키지의 User이므로 글쓴이에 해당되는 author 속성은 User모델을 ForeignKey로 적용
    subject = models.CharField(max_length=200) #질문제목
    content = models.TextField() #글자수 제한 X
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)#질문이나 답변이 언제 수정되었는지 확인
    #null=True의 의미는 modify_date를 데이터베이스에 저장할때 null이 허용된다는 의미, blank=True의 의미는 입력 폼 데이터 체크시(form.is_valid()) 값이 없어도 오류를 내지 않는다는 의미
    voter = models.ManyToManyField(User, related_name='voter_question')  # voter 추가, ManyToManyField관계는 다대다관계의미.

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #답변해당질문
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) #댓글작성자
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)  # 댓글의 질문
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)  # 댓글의 답변

doubleboard/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerDoubleForm
from ..models import QuestionDouble, AnswerDouble

@login_required(login_url='common:login')#로그아웃 상태에서 @login_required 어노테이션이 적용된 함수가 호출되면 자동으로 로그인 화면으로 이동
def answer_create(request, question_id):
    """
    doubleboard 답변등록
    """
    question = get_object_or_404(QuestionDouble, pk=question_id)
    if request.method == "POST":
        form = AnswerDoubleForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author_double = request.user  # 추가한 속성 author 적용, reqeust.user는 현재 로그인한 계정의 User모델 객체
            answer.create_dat_double = timezone.now()
            answer.question_double = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('doubleboard:detail', question_id=question.id), answer.id))#redirect함수는 페이지 이동을 위해 장고가 제공하는 함수, #QuestionDouble과 AnswerDouble 모델은 서로 ForeignKey 로 연결되어 있기때문에  question.answer_set은 질문의 답변을 의미
    else:
        form = AnswerDoubleForm()
    context = {'question': question, 'form': form}
    return render(request, 'doubleboard/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    doubleboard 답변수정
    """
    answer = get_object_or_404(AnswerDouble, pk=answer_id)
    if request.user != answer.author_double:
        messages.error(request, '수정권한이 없습니다')
        return redirect('doubleboard:detail', question_id=answer.question_double.id)

    if request.method == "POST":
        form = AnswerDoubleForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author_double = request.user
            answer.modify_date_double = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('doubleboard:detail', question_id=answer.question_double.id), answer.id)) #doubleboard:detail url에 #answer_7와같은 앵커태그를 추가하기 위해 format, resolve_url사용. resolve_url은 실제 호출되는 url 문자열을 리턴해주는 장고함수.
    else:
        form = AnswerDoubleForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'doubleboard/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    doubleboard 답변삭제
    """
    answer = get_object_or_404(AnswerDouble, pk=answer_id)
    if request.user != answer.author_double:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('doubleboard:detail', question_id=answer.question_double.id)

doubleboard/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentDoubleForm
from ..models import QuestionDouble, AnswerDouble, CommentDouble

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    doubleboard 질문댓글등록
    """
    question = get_object_or_404(QuestionDouble, pk=question_id)
    if request.method == "POST":
        form = CommentDoubleForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author_double = request.user
            comment.create_date_double = timezone.now()
            comment.question_double = question #질문에 대한 댓글이므로 comment에 question저장.
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('doubleboard:detail', question_id=comment.question_double.id), comment.id))
    else:
        form = CommentDoubleForm()
    context = {'form': form}
    return render(request, 'doubleboard/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    doubleboard 질문댓글수정
    """
    comment = get_object_or_404(CommentDouble, pk=comment_id)
    if request.user != comment.author_double:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('doubleboard:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentDoubleForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author_double = request.user
            comment.modify_date_double = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('doubleboard:detail', question_id=comment.question_double.id), comment.id))
    else:
        form = CommentDoubleForm(instance=comment)
    context = {'form': form}
    return render(request, 'doubleboard/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    doubleboard 질문댓글삭제
    """
    comment = get_object_or_404(CommentDouble, pk=comment_id)
    if request.user != comment.author_double:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('doubleboard:detail', question_id=comment.question_id)
    else:
        comment.delete()
    return redirect('doubleboard:detail', question_id=comment.question_id)

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    doubleboard 답글댓글등록
    """
    answer = get_object_or_404(AnswerDouble, pk=answer_id)
    if request.method == "POST":
        form = CommentDoubleForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author_double = request.user
            comment.create_date_double = timezone.now()
            comment.answer_double = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('doubleboard:detail', question_id=comment.answer_double.question_double.id), comment.id))
    else:
        form = CommentDoubleForm()
    context = {'form': form}
    return render(request, 'doubleboard/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    doubleboard 답글댓글수정
    """
    comment = get_object_or_404(CommentDouble, pk=comment_id)
    if request.user != comment.author_double:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('doubleboard:detail', question_id=comment.answer_double.question_double.id)

    if request.method == "POST":
        form = CommentDoubleForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author_double = request.user
            comment.modify_date_double = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('doubleboard:detail', question_id=comment.answer_double.question_double.id), comment.id))
    else:
        form = CommentDoubleForm(instance=comment)
    context = {'form': form}
    return render(request, 'doubleboard/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    doubleboard 답글댓글삭제
    """
    comment = get_object_or_404(CommentDouble, pk=comment_id)
    if request.user != comment.author_double:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('doubleboard:detail', question_id=comment.answer_double.question_double.id)
    else:
        comment.delete()
    return redirect('doubleboard:detail', question_id=comment.answer_double.question_double.id)

doubleboard/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionDoubleForm
from ..models import QuestionDouble

@login_required(login_url='common:login')
def question_create(request):
    """
    doubleboard 질문등록
    """
    if request.method == 'POST':
        form = QuestionDoubleForm(request.POST)# QuestionDoubleForm의 subject와 content에는 request.POST로 전달받은 데이터가 저장
        if form.is_valid():
            question = form.save(commit=False)#commit=False라는 옵션을 사용하면 폼에 연결된 모델을 저장하지 않고 생성된 모델 객체만 리턴
            question.author_double = request.user  # 추가한 속성 author 적용
            question.create_date_double = timezone.now()
            question.save()
            return redirect('doubleboard:index')
    else:
        form = QuestionDoubleForm()
    context = {'form': form}
    return render(request, 'doubleboard/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    doubleboard 질문수정
    """
    question = get_object_or_404(QuestionDouble, pk=question_id)
    if request.user != question.author_double:
        messages.error(request, '수정권한이 없습니다')#messages는 장고가 제공하는 함수로 넌필드 오류(non-field error)를 발생시킬 경우에 사용
        return redirect('doubleboard:detail', question_id=question.id)

    if request.method == "POST": #상세조회 화면에서 "수정" 버튼을 클릭하면 http://localhost:8000/doubleboard/question/modify/2/ 페이지가 GET 방식으로 호출되어 질문수정 화면이 호출되고 질문수정 화면에서 "저장하기" 버튼을 클릭하면 http://localhost:8000/doubleboard/question/modify/2/ 페이지가POST 방식으로 호출되어 데이터가 수정
        form = QuestionDoubleForm(request.POST, instance=question) #조회된 질문의 내용으로 QuestionDoubleForm을 생성하지만 request.POST의 값으로 덮어씀.
        if form.is_valid():
            question = form.save(commit=False)
            question.author_double = request.user
            question.modify_date_double = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('doubleboard:detail', question_id=question.id)
    else:
        form = QuestionDoubleForm(instance=question)#폼 생성시 이처럼 instance값을 지정하면 폼에 값이 채워진 상태로 보여짐(기존 제목, 내용).
    context = {'form': form}
    return render(request, 'doubleboard/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    doubleboard 질문삭제
    """
    question = get_object_or_404(QuestionDouble, pk=question_id)
    if request.user != question.author_double:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('doubleboard:detail', question_id=question.id)
    question.delete()
    return redirect('doubleboard:index')

templates/minorboard/answer_form.html
{% extends 'minorboard.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content_minor">답변내용</label>
            <textarea class="form-control" name="content_minor" id="content_minor" 
                      rows="10">{{ form.content_minor.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/minorboard/comment_form.html
{% extends 'minorboard.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content_minor">댓글내용</label>
            <textarea class="form-control"name="content_minor" id="content_minor" 
                      rows="3">{{ form.content_minor.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/minorboard/question_detail.html
{% extends 'minorboard.html' %}
{% block content %}

<div class="container my-3">  <!--질문이나 답변들은 하나의 뭉치에 해당되므로 부트스트랩의 card 컴포넌트를 사용-->
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject_minor }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter_minor.count}}</div>
            <a href="#" data-uri="{% url 'minorboard:vote_question' question.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문영역 -->
            <div class="card"> <!--my-3은 위아래 방향 마진 3을 의미-->
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ question.content_minor }}</div> <!--글 내용에 줄 바꿈을 정상적으로 보여주기위해 적용한 스타일-->
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date_minor %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date_minor }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left"><!--p-2는 padding 2를 의미-->
                            <div class="mb-2">{{ question.author_minor.username }}</div>
                            <div>{{ question.create_date_minor }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author_minor %}
                    <div class="my-3"><!--수정 버튼은 로그인한 사용자와 글쓴이가 동일한 경우에만 노출되도록 {% if request.user == question.author_minor %}을 적용-->
                        <a href="{% url 'minorboard:question_modify' question.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'minorboard:question_delete' question.id  %}">삭제</a> <!--data-uri 속성은 jQuery에서 $(this).data('uri') 와 같이 사용하여 그 값을 얻을 수 있음-->
                    </div>
                    {% endif %}

                    <!-- 질문 댓글 Start -->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set.all %} <!--질문에 등록된 댓글을 모두 보여줌.-->
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted"> <!--댓글 영역은 작게 나타내기 위해 comment 클래스 사용 설정-->
                            <span style="white-space: pre-line;">{{ comment.content_minor }}</span>
                            <span>
                                - {{ comment.author_minor }}, {{ comment.create_date_minor }}
                                {% if comment.modify_date_minor %}
                                (수정:{{ comment.modify_date_minor }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author_minor %} <!--댓글 작성자와 로그인한 사람 같을 시 수정, 삭제 창 보이도록-->
                            <a href="{% url 'minorboard:comment_modify_question' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'minorboard:comment_delete_question' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'minorboard:comment_create_question' question.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 질문 댓글 End -->
                </div>
            </div>
        </div>
    </div>

    <!--답변구역-->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a> <!--앵커태그-->
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter_minor.count}}</div>
            <a href="#" data-uri="{% url 'minorboard:vote_answer' answer.id  %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">  <!-- 답변영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content_minor }}</div> <!--글 내용에 줄 바꿈을 정상적으로 보여주기위해 적용한 스타일-->
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date_minor %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date_minor }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.author_minor.username }}</div>
                            <div>{{ answer.create_date_minor }}</div>
                        </div>
                    </div>
                    {% if request.user == answer.author_minor %}
                    <div class="my-3">
                        <a href="{% url 'minorboard:answer_modify' answer.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                           data-uri="{% url 'minorboard:answer_delete' answer.id  %}">삭제</a>
                    </div>
                    {% endif %}
                    <!--답변 댓글 start-->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content_minor }}</span>
                            <span>
                                - {{ comment.author_minor }}, {{ comment.create_date_minor }}
                                {% if comment.modify_date_minor %}
                                (수정:{{ comment.modify_date_minor }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author_minor %}
                            <a href="{% url 'minorboard:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'minorboard:comment_delete_answer' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'minorboard:comment_create_answer' answer.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'minorboard:answer_create' question.id %}" method="post" class="my-3"> <!--답변을 저장하는 URL-->
        {% csrf_token %} <!--보안에 관련된 항목으로 form으로 전송된 데이터가 실제 웹페이지에서 작성된 데이터인지를 판단해 주는 가늠자 역할-->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group"><!--답변을 작성하는 textarea에 로그인 상태가 아니라면 disabled 를 지정하여 입력자체를 불가능-->
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content_minor" id="content_minor" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endif %}  <!--여기 수정해야돼 글쓴이 아니면 답변등록 안됨-->
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}